[mgr]
layout         = [ 1, 4, 3 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 0

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 20
image_bound      = [ 0, 0 ] 
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
folder = [
	{ run = 'nvim "$1"', block = true,desc = "neovim", for = "linux" },
	{ run = 'code  "$@"',orphan = true, desc = "vscode" , for = "linux" },
	{ run = 'zeditor  "$@"',orphan = true, desc = "zed" , for = "linux" },
	{ run = '''fish -c "lazygit -p "$1""''', block = true,desc = "lazygit", for = "linux" },
	{ run = 'basename "$@" | xargs -I {} tar --use-compress-program=pigz -cf ~/down/{}.tar.gz {}',orphan = true, desc = "archive" , for = "linux"  },

]
archive = [
	# { run = 'basename "$@" | xargs tar xf ', orphan = true, desc = "tar xf" , for = "linux" },
	# { run = 'basename "$@" | xargs tar xzf ', orphan = true, desc = "tar xzf" , for = "linux" },
	# { run = 'unzip "$1"', orphan = true, desc = "unzip" , for = "linux" },
	# { run = 'unar "$1"', orphan = true, desc = "unrar" , for = "linux" },
	{ run = 'ouch decompress "$1" ', orphan = true, desc = "ouch decompress" , for = "linux" },
]

zip = [
	# { run = 'basename "$@" | xargs tar xf ', orphan = true, desc = "tar xf" , for = "linux" },
	# { run = 'basename "$@" | xargs tar xzf ', orphan = true, desc = "tar xzf" , for = "linux" },
	{ run = 'unzip "$1"', orphan = true, desc = "unzip" , for = "linux" },
	# { run = 'unar "$1"', orphan = true, desc = "unrar" , for = "linux" },
]

text = [
	{ run = 'nvim "$1"', block = true,desc = "neovim", for = "linux" },
	{ run = 'code  "$@"',orphan = true, desc = "vscode" , for = "linux" },
	{ run = 'zeditor  "$@"',orphan = true, desc = "zed" , for = "linux" },
	{ run = 'gedit "$@" ', block = true, orphan = true, desc = "gedit"  , for = "linux"},
	{ run = 'zathura "$@"',orphan = true, desc = "zathura"  , for = "linux" },
]
image = [
	{ run = 'imv "$@"',  orphan = true, desc = "imv" , for = "linux"},
	{ run = 'gthumb "$@"',  orphan = true, desc = "gthumb" , for = "linux"},
]
video = [
	{ run = 'mpv "$@" ', orphan = true, desc = "mpv" , for = "linux" },
	{ run = 'ffmpeg -i "$@" -vf "fps=10" -loop 0 "$@".gif', orphan = true, desc = "change to gif"  , for = "linux" },	

]
audio = [
	{ run = 'mpv "$@" ' , orphan = true, desc = "mpv" , for = "linux"},
]

document = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "xdg-open" , for = "linux" },
	{ run = 'thorium "$@" ' , orphan = true, desc = "thorium" , for = "linux"},
	{ run = 'okular "$@" ' , orphan = true, desc = "okular" , for = "linux"},
	# { run = 'foliate "$@" ' , orphan = true, desc = "foliate" , for = "linux"},
]

fallback = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "xdg-open" , for = "linux" },
	{ run = 'nvim "$1"', block = true,desc = "neovim", for = "linux" },
	{ run = 'nemo "$1"', block = true,desc = "nemo", for = "linux" },
]

[open]
rules = [
	{ url = "*/", use = ["folder"] },

	{ mime = "text/*", use = ["text"] },
	{ mime = "image/*", use = ["image"] },
	{ mime = "video/*", use = ["video"] },
	{ mime = "application/octet-stream",use = ["video"]},
	{ mime = "audio/*", use = ["audio"] },
	{ mime = "inode/empty", use = ["text"] },
	{ mime = "application/json", use = ["text"] },

	{ mime = "application/zip", use = ["zip"] },
	{ mime = "application/gzip", use = ["archive"] },
	{ mime = "application/x-bzip", use = ["archive"] },
	{ mime = "application/x-bzip2", use = ["archive"] },
	{ mime = "application/x-tar", use = ["archive"] },
	{ mime = "application/x-7z-compressed", use = ["archive"] },
	{ mime = "application/x-rar", use = ["archive"] },
	{ mime = "application/pdf", use = ["document"] },
	{ mime = "application/epub+zip", use = ["document"] },
	{ mime = "application/x-mobipocket-ebook", use = ["document"] },

	{ mime = "*", use = ["fallback"] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false

[[plugin.prepend_fetchers]]
id    = "mime" # Remove if Yazi > v26.1.22
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"
group = "mime"

[[plugin.prepend_fetchers]]
id    = "mime" # Remove if Yazi > v26.1.22
url   = "remote://*"
run   = "mime-ext.remote"
prio  = "high"
group = "mime"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*"
run  = "git"
group = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*/"
run  = "git"
group = "git"


[[plugin.prepend_fetchers]]
id   = "current-size"
url = "*"
run  = "current-size"
group = "current-size"

[[plugin.prepend_fetchers]]
id   = "current-size"
url = "*/"
run  = "current-size"
group = "current-size"

[[plugin.prepend_previewers]]
url = "*.epub"
run  = 'epub-preview'
group = "epub"

[[plugin.prepend_previewers]]
url = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
url = "*.docx"
run  = 'piper -- CLICOLOR_FORCE=1 doxx --export ansi --image-width $w -w $w "$1"'

[[plugin.prepend_previewers]]
url = "*.html"
run  = 'piper -- w3m -I UTF-8 -T text/html "$1"'

[[plugin.prepend_previewers]]
mime = "text/html"
run  = 'piper -- w3m -I UTF-8 -T text/html "$1"'

[[plugin.prepend_previewers]]
mime = "application/octet-stream"
run  = "video"

[[plugin.prepend_previewers]]
url = "*.csv"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_preloaders]]
mime = "video/*"
run  = "video-preloader"
